const SHEETS={Expenses:['id','date','category','description','amount','paymentMode','cardId','createdAt','updatedAt'],Income:['id','date','source','description','amount','notes','createdAt','updatedAt'],Loans:['id','name','type','principal','annualRate','tenureMonths','emi','startDate','status','notes','createdAt','updatedAt'],LoanPayments:['id','date','amount','loanId','paymentMode','principalPaid','interestPaid','notes','createdAt','updatedAt'],CreditCards:['id','name','bank','last4','creditLimit','statementDay','dueDay','status','notes','createdAt','updatedAt'],CardPayments:['id','date','amount','cardId','paymentMode','notes','createdAt','updatedAt'],Bills:['id','name','type','provider','amount','dueDay','frequency','status','autoCarryForward','notes','createdAt','updatedAt'],BillPayments:['id','date','amount','billId','paymentMode','notes','createdAt','updatedAt'],Recurring:['id','name','category','amount','frequency','dueDay','paymentMode','active','notes','createdAt','updatedAt'],MonthlySummary:['id','month','income','expenses','balance','emiBills','createdAt','updatedAt'],BudgetCategories:['id','month','category','budget','createdAt','updatedAt']};
function setupV53(){const ss=SpreadsheetApp.getActiveSpreadsheet();Object.keys(SHEETS).forEach(n=>{let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);const h=SHEETS[n];if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);else h.forEach((x,i)=>sh.getRange(1,i+1).setValue(x));sh.setFrozenRows(1)});return {ok:true,version:'5.3',message:'My Budget V5.3 sheets ready',sheets:Object.keys(SHEETS)}}
function doGet(){return json_({ok:true,version:'5.3',message:'My Budget V5.3 backend'})}
function doPost(e){try{return json_(handle_(JSON.parse((e.postData&&e.postData.contents)||'{}')))}catch(err){return json_({ok:false,error:String(err)})}}
function handle_(p){if(p.action==='setup'||p.action==='setupV53')return setupV53();if(p.action==='listAll'){setupV53();let d={};Object.keys(SHEETS).forEach(n=>d[n]=read_(n));return {ok:true,version:'5.3',data:d}}if(p.action==='list'){setupV53();return {ok:true,sheet:p.sheet,data:read_(p.sheet)}}if(p.action==='upsert'){setupV53();upsert_(p.sheet,p.record);return {ok:true,sheet:p.sheet,record:p.record}}if(p.action==='delete'){setupV53();del_(p.sheet,p.id);return {ok:true,sheet:p.sheet,id:p.id}}return {ok:false,error:'Unknown action: '+p.action}}
function read_(n){let sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(n);if(!sh||sh.getLastRow()<2)return [];let v=sh.getDataRange().getValues(),h=v[0].map(String);return v.slice(1).filter(r=>r.some(x=>x!==''&&x!==null)).map(r=>{let o={};h.forEach((k,i)=>o[k]=r[i] instanceof Date?Utilities.formatDate(r[i],Session.getScriptTimeZone(),'yyyy-MM-dd'):r[i]);return o})}
function upsert_(n,r){if(!SHEETS[n])throw Error('Unsupported sheet: '+n);let sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(n),h=SHEETS[n],row=-1;if(r.id&&sh.getLastRow()>1){let ids=sh.getRange(2,1,sh.getLastRow()-1,1).getValues().flat();let i=ids.findIndex(x=>String(x)===String(r.id));if(i>=0)row=i+2}let v=h.map(k=>r[k]??'');if(row<0)sh.appendRow(v);else sh.getRange(row,1,1,h.length).setValues([v])}
function del_(n,id){if(!SHEETS[n])throw Error('Unsupported sheet: '+n);let sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(n);if(sh.getLastRow()<2)return;let ids=sh.getRange(2,1,sh.getLastRow()-1,1).getValues().flat();for(let i=ids.length-1;i>=0;i--)if(String(ids[i])===String(id))sh.deleteRow(i+2)}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
